# Generated by Django 4.2.6 on 2025-01-02 11:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to=account.models.avatar_image_path, verbose_name='تصویر آواتار'),
        ),
    ]
