# Generated by Django 4.2.6 on 2025-02-15 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن تیکت')),
                ('answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('isAnswer', models.BooleanField(default=False, verbose_name='پاسخ تیکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='notifs.ticket', verbose_name='تیکت اصلی')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده تیکت')),
            ],
            options={
                'verbose_name': 'تیکت کاربر',
                'verbose_name_plural': 'تیکت های کاربران',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('seen', models.BooleanField(default=False, verbose_name='مشاهده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifs', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده پیام')),
            ],
            options={
                'verbose_name': 'پیام ادمین',
                'verbose_name_plural': 'پیام های ادمین',
            },
        ),
    ]
