# Generated by Django 4.2.6 on 2025-03-19 04:16

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('is_subcat', models.BooleanField(default=False, verbose_name='موضوع فرعی')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcats', to='blog.category', verbose_name='موضوع اصلی')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, verbose_name='عنوان در آدرس')),
                ('content', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('check', 'در حال بررسی'), ('confirm', 'تایید شده'), ('reject', 'رد شده')], default='check', max_length=10, verbose_name='وضعیت')),
                ('is_draft', models.BooleanField(default=True, verbose_name='ذخیره به عنوان پیش نویس')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.post_image_path, verbose_name='تصویر')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='تگ ها')),
                ('study_time', models.PositiveSmallIntegerField(default=0, help_text='براساس دقیقه', verbose_name='زمان مطالعه')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_posts', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateField(auto_now=True, verbose_name='زمان آخرین لایک')),
                ('posts', models.ManyToManyField(related_name='liked_posts', to='blog.post', verbose_name='پست ها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک کاربر',
                'verbose_name_plural': 'لایک های کاربر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن')),
                ('is_accept', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_answer', models.BooleanField(default=False, verbose_name='پاسخ به کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('main_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.comment', verbose_name='کامنت اصلی')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PostVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='blog.post')),
            ],
            options={
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
