# Generated by Django 4.2.6 on 2025-01-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('check', 'در حال بررسی'), ('confirm', 'تایید شده'), ('reject', 'رد شده')], default='check', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_subcat',
            field=models.BooleanField(default=False, verbose_name='موضوع فرعی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcats', to='blog.category', verbose_name='موضوع اصلی'),
        ),
    ]
