# Generated by Django 4.2.6 on 2025-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, verbose_name='عنوان در آدرس'),
        ),
    ]
