# Generated by Django 4.2.6 on 2025-01-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_lik_count_userlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lik_count',
            new_name='like_count',
        ),
    ]
