# Generated by Django 4.2.6 on 2025-02-03 14:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_lik_count_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='ذخیره به عنوان پیش نویس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_image_path, verbose_name='تصویر'),
        ),
    ]
