# Generated by Django 4.2.6 on 2025-02-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_draft_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_posts', to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
